#!/usr/bin/env bash
# Bash script to Install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
rdt="location /redirect_me {\\nrewrite ^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\\n}"
sudo sed -i "30i $rdt" /etc/nginx/sites-available/default
sudo service nginx restart
