#!/usr/bin/env bash
# Bash script to fix nginx web server

apt-get update -y
apt-get install curl -y
sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[\:\:\]\:8080/listen \[\:\:\]\:80/" /etc/nginx/sites-enabled/default
service nginx restart
