#!/usr/bin/env bash
# Displays username, userid, and home directory path of /etc/passwd in list
input="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
